kind: Service
apiVersion: v1
metadata:
  name: jenkins-ubuntu-slave-svc
  namespace: devops-tools
spec:
  selector:
    app: jenkins-ubuntu-slave
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22